### PR TITLE
Scope colors follow the wire colors of the inputs.

### PR DESCRIPTION
**Pull request by WIZARDISHUNGRY**
scope2scope1
If the wires are the same color, RGB values are shuffled, such that neither X nor Y will match the input color.

scope5scope4scope3

### CODE REVIEW

**Comment by WIZARDISHUNGRY** [comment]
Thinking about the wires being the same color case, it may be sort of annoying to have no easy way of identifying which waveform is which. I'm going to change the "X" and "Y" glyphs in the corner to match the scope.

**Comment by AndrewBelt** [comment]
Ha, this is neat. Tagging @milholen to see this.
I don't accept PRs, but I'll consider adding this feature.

**Comment by AndrewBelt** [comment]
On second thought, I think it's more important to keep the colors fixed since users need to associate the colors with the X and Y knobs, rather than the origin of the signal.

**Comment by WIZARDISHUNGRY** [comment]
Aw, that's a shame 
scope6

**Pull request closed without merging**
