### PR TITLE
New algorithm for Fundamental VCF

### PR DESCRIPTION
**Pull request by musicalentropy**
Side note : I have not tested this in VCV rack yet, I wonder if the resonance is set correctly knowing that it must be bounded between 0 and 1

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Okay, I've fixed the build and made parameter scaling the way I want it, but there are a few issues.
- It doesn't really clip its output. It can still generate large values beyond +/-5V. This should be fixed before merging.
- If DRIVE and FREQ are both high, the LP stutters a bit and HP stutters a LOT.
- Now that it can go to 20kHz, aliasing it very apparent. Perhaps upsample and downsample with dsp/decimator.hpp? Otherwise it should still be limited to 8kHz.

**Comment by musicalentropy** [comment]
Hello !

* For scaling, a solution might be to add another stage of clipping after the filter. I'm not sure the transistor ladder is responsible for the clipping itself, it might be the other electronic stages before and after.
* What do you mean with "stutter" ?
* I'll have a look in decimator.hpp to see how to use it. But now I think also it's time for me to try to compile VCV Rack by myself so I can debug everything properly and prevent any typo

**Comment by AndrewBelt** [comment]
- The ladder definitely does clip the output. Well, in analog ladders. Maybe this model doesn't guarantee clipping.
- Try it and you'll see. Stuttering is not the proper word.
- You can alternatively use the Rack SDK

**Comment by musicalentropy** [comment]
* Well it might be because the model isn't a proper 0df algorithm, the nonlinear part is still "naive" so it doesn't behave exactly like the original, but at least that prevents the need of a proper + CPU hungry algorithm
* I'll test tomorrow the Rack SDK and I'll see what happens with DRIVE+FREQ at high values

**Comment by musicalentropy** [comment]
Quick questions Andrew :

* Do you have a source file which provides upsampling processing ? I have only seen something for downsampling in the dsp folder.
* If you don't, I might write something like the decimator if you want
* All the plug-ins need to provide audio signals with values between -5 and +5 or between -1 and +1 ?

**Comment by AndrewBelt** [comment]
- Lemme write one real quick.
- Audio signals are +/-5V https://vcvrack.com/manual/VoltageStandards.html#audio-and-modulation, but I typically like to give black boxes +/-1V values .

**Comment by musicalentropy** [comment]
The thing is your scope module told me that a signal between -1.f and +1.f (in the DSP code) is between -5 and +5. I did the test with the digital sine in the VCO, and within the VCF code by giving as an output a square wave between -1.f and +1.f. So I was wondering if there is also some mapping between the float values in the DSP code and what you meant with voltages. Then, should I make the output of the VCF clip somehow between -1 and +1 (DSP) => -5 and +5 (scope), or -5 and +5 (DSP) meaning -25 and +25 (scope) ?

**Comment by AndrewBelt** [comment]
Did you notice the `5.f * filter.output[0];` line in VCF.cpp? That's because I give your black box the normalized signals and then convert them back to VCV standard voltages.

**Comment by musicalentropy** [comment]
OK, so there is no mapping at all, that was the thing confusing me, thanks ;)

**Comment by AndrewBelt** [comment]
Added https://github.com/VCVRack/Rack/commit/94a5008d0237d70b60744c7a8654867e04f54444. Sorry, got caught up in other things.

**Comment by musicalentropy** [comment]
Thanks ! I'm doing a lot of experiments right now, I have a 0df version of the filter as well to verify a few things such as the way the signal saturates (that's the algorithm from this article : https://ieeexplore.ieee.org/document/8282295/)

Next on my list is trying the oversampling, and HP filters only structures

**Comment by musicalentropy** [comment]
Hello Andrew ! Have a look to what I have done, I have included three different algorithms, you can grab the one you prefer for branch v0.6

**Comment by AndrewBelt** [comment]
I tried each model, and CPU is too high for all, and only the oversampled version sounds better than the original code. Thinking about just cherry picking my param mapping and reverting to the original model.

**Comment by AndrewBelt** [comment]
Decided to go with the 0df implementation for now. I would like the CPU to be reduced by at least 1/3, but it doesn't look like that's possible because the code is very tighly written.

The highpass still sounds just as bad as the original method, so not sure why I'm persuing the 0df one.

**Comment by musicalentropy** [comment]
Wow you put a lot of efforts in being rude, don’t you ?

**Comment by AndrewBelt** [comment]
My apologies, I don't mean to be rude. I'm just not able to get good results from this, but the effort is appreciated. Perhaps your 0df implementation is good, but maybe there is an arithmetic mistake somewhere?

I'm exploring solving the basic ODE with just the first order method but at a higher sample rate.

**Comment by musicalentropy** [comment]
Apologies accepted ;)

For the HP output problem, I think the correct solution might be to have another independant part of the algorithm made just for that, with 4 HP1 filters in cascade and the feedback loop, instead of getting 5 taps in the original LP algorithm. Without the nonlinearities the maths are fine, and the technique was originally something meant to mimic the Oberheim Xpander filter if I'm not wrong, but not a HP Moog filter, so I don't even know if on the original Moog filters that's how they get their HP outputs...

So what I'm going to do is write the HP4+feedback equations, they will be solved with RK4 too, and we'll see what happens, if it improves the result. We might be able to replace the tanh with a Pade approximation as well (error spread all over the usable rangle, not just minimized around zero), or a lookup table to reduce the CPU load, since in my opinion the oversampling might be mandatory, since it improves the stability for cutoff frequencies higher than 8.5 kHz, and of course removes the aliasing. I'll have a look at that tomorrow.

**Comment by AndrewBelt** [comment]
Any of these routes seem like good options. I feel like preferring quantity over quality of filter output samples is desired, because oversampling solves stability issues near Nyquist as well. The goal is to support resonances up to 10 and drive gains up to 32, while clamping output to roughly +/-5V. Doesn't need to sound super smooth all the time, but it has to be decent across all parameter ranges, because Fundamental VCF is supposed to be pushed to its limits with CV modulation and gain.

**Comment by musicalentropy** [comment]
OK I just did a new commit. Honestly, I'm not sure I could be able to do a lot better with additional work on the algorithm side... Because of the structure of the original Moog filter, it's quite difficult to get a HP output which is clamped other than by adding some extra clamping, I had that problem both in the multi-mode case and with a structure having only HP filters. So I ended up creating a new algorithm which is absolutely correct when it is linear using the TPT structure (but resonance can't be higher than 4 like in the original), and I added "naive tanh" on top of the structure so I don't have to use Newton-Raphson. Tell me what you think about it, and if it's not satisfying enough, we might ask his opinion to the other guy who proposed his help on Facebook ;)

I added an approximation of tanh as well in the code, we might make it even more simple to have a perfect sigmoid without any branching maybe...

**Pull request merged**
