### PR TITLE
Fix modules to do lights the new way, after Rack bc619644.

### PR DESCRIPTION
**Pull request by mdemanett**
Perhaps I just picked a lousy time to build this stuff from master, and should have just waited a minute, but anyway, here's a fix for these modules to build with the changes to how lights work in: https://github.com/VCVRack/Rack/commit/bc619644ac62fdc4fb9b6d6be206789f749ba857

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Thanks!

**Comment by AndrewBelt** [comment]
Note that GreenRedLight and anything else that adds two colors require two adjacent `lightId`s. So it would use `lightId` and `lightId + 1`.

**Comment by AndrewBelt** [comment]
You also inverted the states of Lissajous mode and External mode.

**Comment by mdemanett** [comment]
The two IDs thing explains a lot.  I see that you fixed it up, thank you.

**Pull request merged**
